from fpdf import FPDF
import json
import re

def sanitize(text: str) -> str:
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "\u2014": "-",   # em dash
        "\u2013": "-",   # en dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2026": "...", # ellipsis
        "\u00e9": "e",   # é
        "\u00e0": "a",   # à
        "\u00fc": "u",   # ü
        "\u2022": "-",   # bullet
        "\u25b2": "^",   # up triangle
        "\u25bc": "v",   # down triangle
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Remove any remaining non-latin-1 characters
    text = text.encode("latin-1", errors="ignore").decode("latin-1")
    return text


class BizlyticsPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(59, 130, 246)
        self.cell(0, 10, "BIZLYTICS - AI Business Intelligence Report", align="C")
        self.set_draw_color(59, 130, 246)
        self.line(10, 18, 200, 18)
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} - Generated by Bizlytics", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(59, 130, 246)
        self.set_fill_color(240, 245, 255)
        self.cell(0, 8, sanitize(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        self.set_text_color(0, 0, 0)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, sanitize(text))
        self.ln(2)

    def kpi_table(self, kpis: dict):
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(59, 130, 246)
        self.set_text_color(255, 255, 255)
        col_w = [70, 35, 35, 35, 25]
        headers = ["Metric", "Total", "Average", "Max", "Trend"]
        for i, h in enumerate(headers):
            self.cell(col_w[i], 8, h, fill=True, border=1)
        self.ln()

        self.set_font("Helvetica", "", 9)
        fill = False
        for name, kpi in list(kpis.items())[:15]:
            if name == "_domain_kpis":
                continue
            self.set_fill_color(245, 248, 255) if fill else self.set_fill_color(255, 255, 255)
            self.set_text_color(30, 30, 30)
            trend = kpi.get("trend", "-")
            trend_symbol = "UP" if trend == "up" else ("DOWN" if trend == "down" else "-")
            row = [
                sanitize(name.replace("_", " ").title()[:30]),
                f"{kpi.get('total', 0):,.2f}",
                f"{kpi.get('average', 0):,.2f}",
                f"{kpi.get('max', 0):,.2f}",
                trend_symbol
            ]
            for i, cell in enumerate(row):
                self.cell(col_w[i], 7, sanitize(str(cell)), border=1, fill=True)
            self.ln()
            fill = not fill
        self.ln(4)

    def insight_cards(self, items: list, color: tuple):
        self.set_font("Helvetica", "", 10)
        for item in items[:5]:
            self.set_fill_color(*color)
            self.set_text_color(30, 30, 30)
            title = sanitize(item.get("title", ""))
            desc = sanitize(item.get("description", ""))
            badge = item.get("sentiment") or item.get("impact") or item.get("priority") or ""
            self.set_font("Helvetica", "B", 10)
            self.cell(0, 7, sanitize(f"  {title}  [{badge.upper()}]"), fill=True, new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 9)
            self.set_text_color(80, 80, 80)
            self.set_x(14)
            self.multi_cell(0, 5, desc)
            self.ln(2)


def generate_pdf(
    domain: dict,
    data_quality: dict,
    kpis: dict,
    anomalies: dict,
    insights: dict,
    file_id: str
) -> bytes:
    pdf = BizlyticsPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title Block
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 12, "Business Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8,
        sanitize(f"Domain: {domain.get('label', 'General')}   |   File ID: {file_id[:8]}..."),
        align="C", new_x="LMARGIN", new_y="NEXT"
    )
    pdf.ln(6)

    # Dataset Overview
    pdf.section_title("Dataset Overview")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    stats = [
        ("Total Rows", data_quality.get("total_rows", "N/A")),
        ("Total Columns", data_quality.get("total_columns", "N/A")),
        ("Duplicate Rows", data_quality.get("duplicate_rows", 0)),
        ("Anomalies Found", anomalies.get("anomaly_count", 0)),
    ]
    for label, val in stats:
        pdf.cell(60, 7, sanitize(f"  {label}:"), border=0)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, sanitize(str(val)), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
    pdf.ln(4)

    # Executive Summary
    if insights.get("executive_summary"):
        pdf.section_title("AI Executive Summary")
        pdf.body_text(insights["executive_summary"])

    # KPIs
    if kpis:
        pdf.section_title("Key Performance Indicators")
        pdf.kpi_table(kpis)

    # Trends
    if insights.get("trends"):
        pdf.section_title("Trends Identified")
        pdf.insight_cards(insights["trends"], (230, 255, 235))

    # Risks
    if insights.get("risks"):
        pdf.section_title("Risks Identified")
        pdf.insight_cards(insights["risks"], (255, 235, 235))

    # Opportunities
    if insights.get("opportunities"):
        pdf.section_title("Opportunities")
        pdf.insight_cards(insights["opportunities"], (255, 250, 220))

    # Recommendations
    if insights.get("recommendations"):
        pdf.section_title("Recommendations")
        pdf.set_font("Helvetica", "", 10)
        for i, rec in enumerate(insights["recommendations"][:6], 1):
            priority = rec.get("priority", "").upper()
            action = sanitize(rec.get("action", ""))
            outcome = sanitize(rec.get("outcome", ""))
            color = (200, 0, 0) if priority == "HIGH" else (180, 130, 0) if priority == "MEDIUM" else (0, 150, 0)
            pdf.set_text_color(*color)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, sanitize(f"  {i}. [{priority}] {action}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.set_x(18)
            pdf.multi_cell(0, 5, sanitize(f"Expected outcome: {outcome}"))
            pdf.ln(1)

    # Anomaly Summary
    if anomalies.get("anomaly_count", 0) > 0:
        pdf.section_title(f"Anomaly Summary - {anomalies['anomaly_count']} detected")
        for rc in (anomalies.get("root_causes") or [])[:5]:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(180, 30, 30)
            pdf.cell(0, 6, sanitize(f"  Row #{rc['row_index']}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(60, 60, 60)
            for reason in rc.get("top_reasons", [])[:3]:
                pdf.set_x(16)
                pdf.cell(0, 5,
                    sanitize(
                        f"{reason['column']}: {reason['value']} "
                        f"(avg: {reason['normal_avg']}, deviation: {reason['pct_diff']}%)"
                    ),
                    new_x="LMARGIN", new_y="NEXT"
                )
            pdf.ln(2)

    return bytes(pdf.output())
