from fpdf import FPDF


def sanitize(text) -> str:
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "\u2014": "-", "\u2013": "-",
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2026": "...", "\u2022": "-",
        "\u25b2": "^", "\u25bc": "v",
        "\u00e9": "e", "\u00e0": "a",
        "\u00fc": "u", "\u00f6": "o",
        "\u00e4": "a", "\u00f1": "n",
        "\u00df": "ss", "\u20ac": "EUR",
        "\u00a3": "GBP", "\u00a5": "JPY",
        "\u2190": "<-", "\u2192": "->",
        "\u2191": "^", "\u2193": "v",
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    text = text.encode("latin-1", errors="ignore").decode("latin-1")
    return text


def fmt_num(val) -> str:
    """Safely format a number or return the value as string."""
    try:
        f = float(val)
        if abs(f) >= 1_000_000:
            return f"{f/1_000_000:.2f}M"
        if abs(f) >= 1_000:
            return f"{f:,.2f}"
        return f"{f:.2f}"
    except (TypeError, ValueError):
        return sanitize(str(val)) if val is not None else "N/A"


class BizlyticsPDF(FPDF):

    # ── Page layout constants ────────────────────────────────────────────
    BLUE       = (59, 130, 246)
    DARK       = (20, 20, 20)
    GRAY       = (100, 100, 100)
    LIGHT_GRAY = (150, 150, 150)
    RED        = (200, 40, 40)
    ORANGE     = (180, 110, 0)
    GREEN_TEXT = (20, 140, 60)

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.BLUE)
        self.cell(0, 8, "BIZLYTICS  -  AI-Powered Business Intelligence Report", align="C")
        self.set_draw_color(*self.BLUE)
        self.line(10, 16, 200, 16)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.LIGHT_GRAY)
        self.cell(0, 10, f"Page {self.page_no()}  -  Generated by Bizlytics", align="C")

    def section_title(self, title: str):
        self.ln(2)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.BLUE)
        self.set_fill_color(237, 244, 255)
        self.cell(0, 8, sanitize(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 220, 255)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_text_color(*self.DARK)

    def sub_title(self, title: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(60, 60, 60)
        self.cell(0, 6, sanitize(title), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, sanitize(text))
        self.ln(2)

    def two_col_stats(self, stats: list):
        """Render a list of (label, value) tuples in two columns."""
        self.set_font("Helvetica", "", 10)
        col_w = 95
        for i, (label, val) in enumerate(stats):
            if i % 2 == 0 and i > 0:
                self.ln()
            self.set_text_color(*self.GRAY)
            self.cell(45, 7, sanitize(f"{label}:"))
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(*self.DARK)
            self.cell(col_w - 45, 7, sanitize(str(val)))
            self.set_font("Helvetica", "", 10)
        self.ln(8)

    def kpi_table(self, kpis: dict):
        col_w = [68, 32, 32, 32, 22, 14]
        headers = ["Metric", "Total", "Average", "Max", "Growth%", "Trend"]

        # Header row
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(*self.BLUE)
        self.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            self.cell(col_w[i], 8, h, fill=True, border=1, align="C")
        self.ln()

        # Data rows
        self.set_font("Helvetica", "", 9)
        fill = False
        for name, kpi in list(kpis.items())[:20]:
            if name == "_domain_kpis":
                continue
            if not isinstance(kpi, dict):
                continue
            self.set_fill_color(245, 248, 255) if fill else self.set_fill_color(255, 255, 255)
            self.set_text_color(30, 30, 30)

            trend = kpi.get("trend", "-")
            trend_sym = "UP" if trend == "up" else ("DOWN" if trend == "down" else "-")
            growth = kpi.get("growth_rate")
            growth_str = f"{growth:+.1f}" if isinstance(growth, (int, float)) else "-"

            row = [
                sanitize(name.replace("_", " ").title()[:32]),
                fmt_num(kpi.get("total")),
                fmt_num(kpi.get("average")),
                fmt_num(kpi.get("max")),
                growth_str,
                trend_sym,
            ]
            for i, cell_val in enumerate(row):
                align = "L" if i == 0 else "R"
                self.cell(col_w[i], 7, sanitize(str(cell_val)), border=1, fill=True, align=align)
            self.ln()
            fill = not fill
        self.ln(4)

    def domain_kpi_table(self, domain_kpis: dict):
        """Smaller table for domain-specific smart KPIs."""
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(100, 60, 200)
        self.set_text_color(255, 255, 255)
        self.cell(100, 7, "Smart KPI", fill=True, border=1)
        self.cell(90, 7, "Value", fill=True, border=1)
        self.ln()

        self.set_font("Helvetica", "", 9)
        fill = False
        for key, val in list(domain_kpis.items())[:10]:
            self.set_fill_color(248, 245, 255) if fill else self.set_fill_color(255, 255, 255)
            self.set_text_color(30, 30, 30)
            self.cell(100, 7, sanitize(key.replace("_", " ").title()), border=1, fill=True)
            self.cell(90, 7, fmt_num(val), border=1, fill=True, align="R")
            self.ln()
            fill = not fill
        self.ln(4)

    def insight_cards(self, items: list, bg_color: tuple):
        self.set_font("Helvetica", "", 10)
        for item in items[:6]:
            title = sanitize(item.get("title", ""))
            desc  = sanitize(item.get("description", ""))
            badge = (
                item.get("sentiment") or
                item.get("impact") or
                item.get("priority") or ""
            ).upper()

            # Badge color
            if badge in ("POSITIVE", "LOW"):
                self.set_text_color(*self.GREEN_TEXT)
            elif badge in ("NEGATIVE", "HIGH"):
                self.set_text_color(*self.RED)
            else:
                self.set_text_color(*self.ORANGE)

            self.set_fill_color(*bg_color)
            self.set_font("Helvetica", "B", 10)
            self.cell(
                0, 7,
                sanitize(f"  {title}  [{badge}]") if badge else sanitize(f"  {title}"),
                fill=True, new_x="LMARGIN", new_y="NEXT"
            )
            self.set_font("Helvetica", "", 9)
            self.set_text_color(70, 70, 70)
            self.set_x(14)
            self.multi_cell(0, 5, desc)
            self.ln(2)

    def anomaly_card(self, rc: dict, idx: int):
        """Render one anomaly root cause card — handles both numeric and categorical."""
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.RED)
        anomaly_types = rc.get("anomaly_types", ["numeric"])
        type_str = " + ".join(anomaly_types) if anomaly_types else "numeric"
        self.cell(
            0, 6,
            sanitize(f"  Row #{rc['row_index']}  [{type_str}]"),
            new_x="LMARGIN", new_y="NEXT"
        )

        self.set_font("Helvetica", "", 9)
        self.set_text_color(60, 60, 60)

        for reason in rc.get("top_reasons", [])[:3]:
            col = reason.get("column", "?")
            val = reason.get("value", "?")
            reason_type = reason.get("type", "numeric")

            if reason_type == "categorical":
                # Categorical reason — has a text explanation
                reason_text = reason.get("reason", f"Unusual value '{val}' in column '{col}'")
                self.set_x(16)
                self.multi_cell(0, 5, sanitize(f"• {reason_text}"))
            else:
                # Numeric reason — has normal_avg and pct_diff
                normal_avg = reason.get("normal_avg")
                pct_diff   = reason.get("pct_diff")
                avg_str  = fmt_num(normal_avg) if normal_avg is not None else "N/A"
                diff_str = f"{pct_diff:+.1f}%" if isinstance(pct_diff, (int, float)) else "N/A"
                self.set_x(16)
                self.cell(
                    0, 5,
                    sanitize(f"• {col}: {fmt_num(val)}  (avg: {avg_str}, deviation: {diff_str})"),
                    new_x="LMARGIN", new_y="NEXT"
                )
        self.ln(3)


# ── Main entry point ───────────────────────────────────────────────────────

def generate_pdf(
    domain: dict,
    data_quality: dict,
    kpis: dict,
    anomalies: dict,
    insights: dict,
    file_id: str,
    forecast: dict = None,
) -> bytes:
    pdf = BizlyticsPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Cover block ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*BizlyticsPDF.DARK)
    pdf.cell(0, 12, "Business Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*BizlyticsPDF.GRAY)
    domain_label = domain.get("label", "General Dataset") if domain else "General Dataset"
    pdf.cell(
        0, 8,
        sanitize(f"Domain: {domain_label}   |   File: {file_id[:12]}..."),
        align="C", new_x="LMARGIN", new_y="NEXT"
    )
    pdf.ln(6)

    # ── Dataset overview ───────────────────────────────────────────────────
    pdf.section_title("Dataset Overview")
    quality_score = data_quality.get("quality_score", "N/A")
    missing_pct   = data_quality.get("missing_pct", "N/A")
    stats = [
        ("Total Rows",       data_quality.get("total_rows", "N/A")),
        ("Total Columns",    data_quality.get("total_columns", "N/A")),
        ("Missing Data",     f"{missing_pct}%"),
        ("Duplicate Rows",   data_quality.get("duplicate_rows", 0)),
        ("Quality Score",    f"{quality_score}/100"),
        ("Anomalies Found",  anomalies.get("anomaly_count", 0)),
    ]
    pdf.two_col_stats(stats)

    # ── Executive summary ──────────────────────────────────────────────────
    if insights.get("executive_summary"):
        pdf.section_title("AI Executive Summary")
        pdf.body_text(insights["executive_summary"])

    # ── KPIs ───────────────────────────────────────────────────────────────
    if kpis:
        clean_kpis = {k: v for k, v in kpis.items() if k != "_domain_kpis"}
        if clean_kpis:
            pdf.section_title("Key Performance Indicators")
            pdf.kpi_table(clean_kpis)

        domain_kpis = kpis.get("_domain_kpis", {})
        if domain_kpis and isinstance(domain_kpis, dict):
            pdf.sub_title(f"{domain_label} — Smart KPIs")
            pdf.domain_kpi_table(domain_kpis)

    # ── Forecast summary ───────────────────────────────────────────────────
    if forecast and forecast.get("forecast"):
        pdf.section_title("Forecast Summary")
        trend_dir = forecast.get("trend_direction", "stable")
        fc_rows   = forecast["forecast"]
        pdf.body_text(
            f"Trend direction: {trend_dir.upper()}  |  "
            f"Forecast periods: {len(fc_rows)}  |  "
            f"Model: Prophet"
        )
        # Show last 5 forecast points
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(*BizlyticsPDF.BLUE)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(80, 7, "Date", fill=True, border=1)
        pdf.cell(50, 7, "Forecast", fill=True, border=1)
        pdf.cell(50, 7, "Confidence (low-high)", fill=True, border=1)
        pdf.ln()
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*BizlyticsPDF.DARK)
        for row in fc_rows[-5:]:
            pdf.set_fill_color(245, 248, 255)
            pdf.cell(80, 6, sanitize(str(row.get("ds", ""))[:20]), border=1, fill=True)
            pdf.cell(50, 6, fmt_num(row.get("yhat")), border=1, fill=True, align="R")
            lo = fmt_num(row.get("yhat_lower"))
            hi = fmt_num(row.get("yhat_upper"))
            pdf.cell(50, 6, sanitize(f"{lo} - {hi}"), border=1, fill=True, align="R")
            pdf.ln()
        pdf.ln(4)

    # ── Trends ─────────────────────────────────────────────────────────────
    if insights.get("trends"):
        pdf.section_title("Trends Identified")
        pdf.insight_cards(insights["trends"], (230, 255, 235))

    # ── Risks ──────────────────────────────────────────────────────────────
    if insights.get("risks"):
        pdf.section_title("Risks Identified")
        pdf.insight_cards(insights["risks"], (255, 235, 235))

    # ── Opportunities ──────────────────────────────────────────────────────
    if insights.get("opportunities"):
        pdf.section_title("Opportunities")
        pdf.insight_cards(insights["opportunities"], (255, 250, 220))

    # ── Recommendations ────────────────────────────────────────────────────
    if insights.get("recommendations"):
        pdf.section_title("Recommendations")
        for i, rec in enumerate(insights["recommendations"][:6], 1):
            priority = rec.get("priority", "").upper()
            action   = sanitize(rec.get("action", ""))
            outcome  = sanitize(rec.get("outcome", ""))

            if priority == "HIGH":
                pdf.set_text_color(*BizlyticsPDF.RED)
            elif priority == "MEDIUM":
                pdf.set_text_color(*BizlyticsPDF.ORANGE)
            else:
                pdf.set_text_color(*BizlyticsPDF.GREEN_TEXT)

            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(
                0, 7,
                sanitize(f"  {i}. [{priority}] {action}"),
                new_x="LMARGIN", new_y="NEXT"
            )
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.set_x(18)
            pdf.multi_cell(0, 5, sanitize(f"Expected: {outcome}"))
            pdf.ln(1)
        pdf.ln(2)

    # ── Anomaly summary ────────────────────────────────────────────────────
    anomaly_count = anomalies.get("anomaly_count", 0)
    if anomaly_count > 0:
        pdf.section_title(f"Anomaly Summary  —  {anomaly_count} detected")

        # Detection method breakdown if available
        det = anomalies.get("detection_summary", {})
        if det:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*BizlyticsPDF.GRAY)
            pdf.cell(
                0, 6,
                sanitize(
                    f"Numeric consensus: {det.get('numeric_consensus_flagged', 0)}  |  "
                    f"Group-aware: {det.get('group_aware_flagged', 0)}  |  "
                    f"Categorical: {det.get('categorical_flagged', 0)}"
                ),
                new_x="LMARGIN", new_y="NEXT"
            )
            pdf.ln(2)

        for rc in (anomalies.get("root_causes") or [])[:8]:
            pdf.anomaly_card(rc, 0)

        # Soft categorical flags
        soft = anomalies.get("soft_categorical_flags", [])
        if soft:
            pdf.sub_title(f"Soft Categorical Signals  ({len(soft)} rows)")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(100, 80, 0)
            for flag in soft[:5]:
                reasons = "; ".join(flag.get("reasons", []))
                pdf.set_x(14)
                pdf.multi_cell(0, 5, sanitize(f"Row #{flag['row_index']}: {reasons}"))
            pdf.ln(2)

    return bytes(pdf.output())
