from fpdf import FPDF
from datetime import datetime



# ── Helpers ────────────────────────────────────────────────────────────────


def sanitize(text) -> str:
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "\u2014": "-", "\u2013": "-",
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2026": "...", "\u2022": "-",
        "\u25b2": "^", "\u25bc": "v",
        "\u00e9": "e", "\u00e0": "a",
        "\u00fc": "u", "\u00f6": "o",
        "\u00e4": "a", "\u00f1": "n",
        "\u00df": "ss", "\u20ac": "EUR",
        "\u00a3": "GBP", "\u00a5": "JPY",
        "\u2190": "<-", "\u2192": "->",
        "\u2191": "^", "\u2193": "v",
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    text = text.encode("latin-1", errors="ignore").decode("latin-1")
    return text



def fmt_num(val) -> str:
    try:
        f = float(val)
        if abs(f) >= 1_000_000:
            return f"{f/1_000_000:.2f}M"
        if abs(f) >= 1_000:
            return f"{f:,.2f}"
        return f"{f:.2f}"
    except (TypeError, ValueError):
        return sanitize(str(val)) if val is not None else "N/A"



# ── PDF Class ──────────────────────────────────────────────────────────────


class BizlyticsPDF(FPDF):


    # ── Colour palette ──────────────────────────────────────────────────
    BLUE        = (59, 130, 246)
    BLUE_DARK   = (37,  99, 235)
    PURPLE      = (124, 58, 237)
    DARK        = (15,  23,  42)
    GRAY        = (100, 116, 139)
    LIGHT_GRAY  = (148, 163, 184)
    BG_BLUE     = (239, 246, 255)
    BG_PURPLE   = (245, 243, 255)
    BG_GREEN    = (236, 253, 245)
    BG_RED      = (254, 242, 242)
    BG_YELLOW   = (254, 252, 232)
    RED         = (220,  38,  38)
    ORANGE      = (217, 119,   6)
    GREEN_TEXT  = (5,  150,  105)
    WHITE       = (255, 255, 255)
    INDIGO      = (99,  102, 241)
    BG_INDIGO   = (238, 242, 255)


    # ── Header / Footer ─────────────────────────────────────────────────


    def header(self):
        if self.page_no() == 1:
            return
        self.set_fill_color(*self.DARK)
        self.rect(0, 0, 210, 14, "F")
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*self.WHITE)
        self.set_y(3)
        self.cell(0, 8, "BIZLYTICS  |  AI-Powered Business Intelligence", align="C")
        self.set_text_color(*self.DARK)
        self.set_y(18)


    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-14)
        self.set_draw_color(*self.BLUE)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.LIGHT_GRAY)
        self.cell(0, 10, f"Page {self.page_no() - 1}  |  Generated by Bizlytics  |  Confidential", align="C")


    # ── Cover page (analysis) ───────────────────────────────────────────


    def cover_page(self, domain_label: str, file_id: str, data_quality: dict, anomaly_count: int):
        self.set_fill_color(*self.DARK)
        self.rect(0, 0, 210, 297, "F")
        self.set_fill_color(*self.BLUE)
        self.rect(0, 0, 210, 6, "F")

        self.set_y(30)
        self.set_font("Helvetica", "B", 32)
        self.set_text_color(*self.WHITE)
        self.cell(0, 14, "Bizlytics", align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 12)
        self.set_text_color(*self.LIGHT_GRAY)
        self.cell(0, 8, "AI-Powered Business Intelligence", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(10)
        self.set_draw_color(*self.BLUE)
        self.set_line_width(1)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(14)

        self.set_font("Helvetica", "B", 22)
        self.set_text_color(*self.WHITE)
        self.cell(0, 12, "Business Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(4)
        self.set_font("Helvetica", "", 13)
        self.set_text_color(147, 197, 253)
        self.cell(0, 8, sanitize(domain_label), align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(20)
        stats = [
            ("Rows Analysed",  str(data_quality.get("total_rows", "N/A"))),
            ("Columns",        str(data_quality.get("total_columns", "N/A"))),
            ("Quality Score",  f"{data_quality.get('quality_score', 'N/A')}/100"),
            ("Anomalies",      str(anomaly_count)),
        ]
        card_w = 40
        total_w = card_w * len(stats) + 6 * (len(stats) - 1)
        start_x = (210 - total_w) / 2

        for i, (label, value) in enumerate(stats):
            x = start_x + i * (card_w + 6)
            self.set_fill_color(30, 41, 59)
            self.rounded_rect(x, self.get_y(), card_w, 22, 3, "F")
            self.set_font("Helvetica", "B", 14)
            self.set_text_color(*self.WHITE)
            self.set_xy(x, self.get_y() + 3)
            self.cell(card_w, 8, sanitize(value), align="C")
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*self.LIGHT_GRAY)
            self.set_xy(x, self.get_y() + 9)
            self.cell(card_w, 6, sanitize(label), align="C")

        self.ln(36)

        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.LIGHT_GRAY)
        generated_at = datetime.now().strftime("%d %B %Y, %I:%M %p")
        self.cell(0, 6, sanitize(f"File ID: {file_id[:16]}...   |   Generated: {generated_at}"), align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_fill_color(*self.BLUE)
        self.rect(0, 291, 210, 6, "F")


    # ── Cover page (comparison) ─────────────────────────────────────────


    def cover_page_comparison(
        self,
        mode: str,          # "two" or "multi"
        labels: list,
        metrics_compared: int,
        significant_changes: int,
        file_count: int = 2,
    ):
        """Dark cover page styled for comparison reports."""
        self.set_fill_color(*self.DARK)
        self.rect(0, 0, 210, 297, "F")

        # Top gradient bar (purple for comparison theme)
        self.set_fill_color(*self.PURPLE)
        self.rect(0, 0, 210, 6, "F")

        # Logo
        self.set_y(30)
        self.set_font("Helvetica", "B", 32)
        self.set_text_color(*self.WHITE)
        self.cell(0, 14, "Bizlytics", align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 12)
        self.set_text_color(*self.LIGHT_GRAY)
        self.cell(0, 8, "AI-Powered Business Intelligence", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(10)
        self.set_draw_color(*self.PURPLE)
        self.set_line_width(1)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(14)

        # Report type
        report_title = "Dataset Comparison Report" if mode == "two" else "Multi-Period Comparison Report"
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(*self.WHITE)
        self.cell(0, 12, report_title, align="C", new_x="LMARGIN", new_y="NEXT")

        # Labels subtitle
        self.ln(4)
        self.set_font("Helvetica", "", 11)
        self.set_text_color(196, 181, 253)
        label_str = "  vs  ".join(labels) if mode == "two" else "  ->  ".join(labels)
        # truncate if too long
        if len(label_str) > 60:
            label_str = label_str[:57] + "..."
        self.cell(0, 8, sanitize(label_str), align="C", new_x="LMARGIN", new_y="NEXT")

        # Stat cards
        self.ln(20)
        stats = [
            ("Files Compared",      str(file_count)),
            ("Metrics Analysed",    str(metrics_compared)),
            ("Significant Changes", str(significant_changes)),
            ("Report Type",         "AI-Powered"),
        ]
        card_w = 40
        total_w = card_w * len(stats) + 6 * (len(stats) - 1)
        start_x = (210 - total_w) / 2

        for i, (label, value) in enumerate(stats):
            x = start_x + i * (card_w + 6)
            self.set_fill_color(30, 27, 60)
            self.rounded_rect(x, self.get_y(), card_w, 22, 3, "F")
            self.set_font("Helvetica", "B", 14)
            self.set_text_color(*self.WHITE)
            self.set_xy(x, self.get_y() + 3)
            self.cell(card_w, 8, sanitize(value), align="C")
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*self.LIGHT_GRAY)
            self.set_xy(x, self.get_y() + 9)
            self.cell(card_w, 6, sanitize(label), align="C")

        self.ln(36)

        generated_at = datetime.now().strftime("%d %B %Y, %I:%M %p")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.LIGHT_GRAY)
        self.cell(0, 6, sanitize(f"Generated: {generated_at}  |  Bizlytics AI Comparison Engine"), align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_fill_color(*self.PURPLE)
        self.rect(0, 291, 210, 6, "F")


    # ── Section helpers ─────────────────────────────────────────────────


    def section_title(self, title: str, color: tuple = None):
        self.ln(4)
        bg = color or self.BG_BLUE
        accent = self.BLUE if bg == self.BG_BLUE else (
            self.PURPLE if bg == self.BG_PURPLE else (
            self.RED if bg == self.BG_RED else (
            self.INDIGO if bg == self.BG_INDIGO else self.ORANGE
        )))
        self.set_fill_color(*accent)
        self.rect(10, self.get_y(), 3, 9, "F")
        self.set_fill_color(*bg)
        self.rect(13, self.get_y(), 187, 9, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.DARK)
        self.set_x(16)
        self.cell(0, 9, sanitize(title), new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.set_text_color(*self.DARK)


    def sub_title(self, title: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(60, 80, 120)
        self.cell(0, 7, sanitize(title), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)


    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 65, 80)
        self.multi_cell(0, 6, sanitize(text))
        self.ln(2)


    def info_box(self, text: str, bg: tuple = None, text_color: tuple = None):
        bg = bg or self.BG_BLUE
        tc = text_color or self.DARK
        self.set_fill_color(*bg)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*tc)
        self.set_x(10)
        self.multi_cell(0, 7, sanitize(f"  {text}"), fill=True)
        self.ln(2)


    def rounded_rect(self, x, y, w, h, r, style=""):
        self.rect(x, y, w, h, style)


    # ── Stat grid ───────────────────────────────────────────────────────


    def stat_grid(self, stats: list):
        col_w = 58
        gap   = 5
        per_row = 3
        start_x = 10

        for i, (label, value) in enumerate(stats):
            col = i % per_row
            if col == 0 and i > 0:
                self.ln(20)
            x = start_x + col * (col_w + gap)
            y = self.get_y()
            self.set_fill_color(248, 250, 252)
            self.set_draw_color(226, 232, 240)
            self.set_line_width(0.3)
            self.rect(x, y, col_w, 16, "FD")
            self.set_font("Helvetica", "B", 13)
            self.set_text_color(*self.BLUE_DARK)
            self.set_xy(x, y + 1)
            self.cell(col_w, 8, sanitize(str(value)), align="C")
            self.set_font("Helvetica", "", 8)
            self.set_text_color(*self.GRAY)
            self.set_xy(x, y + 8)
            self.cell(col_w, 6, sanitize(label), align="C")
            self.set_xy(start_x, y)
        self.ln(22)


    # ── KPI table ───────────────────────────────────────────────────────


    def kpi_table(self, kpis: dict):
        col_w = [62, 30, 30, 30, 24, 14]
        headers = ["Metric", "Total", "Average", "Max", "Growth %", "Trend"]

        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        for i, h in enumerate(headers):
            self.cell(col_w[i], 9, h, fill=True, border=0, align="C")
        self.ln()

        self.set_font("Helvetica", "", 9)
        for idx, (name, kpi) in enumerate(list(kpis.items())[:20]):
            if name == "_domain_kpis" or not isinstance(kpi, dict):
                continue
            fill_color = (248, 250, 255) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)
            self.set_text_color(*self.DARK)

            trend    = kpi.get("trend", "-")
            trend_sym = "UP" if trend == "up" else ("DN" if trend == "down" else "-")
            growth   = kpi.get("growth_rate")
            growth_s = f"{growth:+.1f}" if isinstance(growth, (int, float)) else "-"

            row = [
                sanitize(name.replace("_", " ").title()[:34]),
                fmt_num(kpi.get("total")),
                fmt_num(kpi.get("average")),
                fmt_num(kpi.get("max")),
                growth_s,
                trend_sym,
            ]
            for i, cell_val in enumerate(row):
                if i == 4 and isinstance(growth, (int, float)):
                    self.set_text_color(*self.GREEN_TEXT if growth >= 0 else self.RED)
                elif i == 5:
                    self.set_text_color(*self.GREEN_TEXT if trend == "up" else (self.RED if trend == "down" else self.GRAY))
                else:
                    self.set_text_color(*self.DARK)
                align = "L" if i == 0 else "R"
                self.cell(col_w[i], 7, sanitize(str(cell_val)), border="B", fill=True, align=align)
            self.ln()
        self.set_draw_color(*self.LIGHT_GRAY)
        self.ln(4)


    # ── Domain KPI table ────────────────────────────────────────────────


    def domain_kpi_table(self, domain_kpis: dict):
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(*self.PURPLE)
        self.set_text_color(*self.WHITE)
        self.cell(100, 8, "Smart KPI", fill=True, border=0)
        self.cell(90,  8, "Value",     fill=True, border=0)
        self.ln()

        self.set_font("Helvetica", "", 9)
        for idx, (key, val) in enumerate(list(domain_kpis.items())[:10]):
            fill_color = (248, 245, 255) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)
            self.set_text_color(*self.DARK)
            self.cell(100, 7, sanitize(key.replace("_", " ").title()), border="B", fill=True)
            self.cell(90,  7, fmt_num(val), border="B", fill=True, align="R")
            self.ln()
        self.ln(4)


    # ── Insight cards ───────────────────────────────────────────────────


    def insight_cards(self, items: list, bg_color: tuple, accent: tuple = None):
        accent = accent or self.BLUE
        self.set_font("Helvetica", "", 10)
        for item in items[:6]:
            title = sanitize(item.get("title", ""))
            desc  = sanitize(item.get("description", ""))
            badge = (item.get("sentiment") or item.get("impact") or item.get("priority") or "").upper()

            self.set_fill_color(*bg_color)
            self.set_draw_color(*accent)
            self.set_line_width(0.2)
            self.set_x(10)

            self.set_font("Helvetica", "B", 10)
            self.set_text_color(*self.DARK)
            title_text = sanitize(f"  {title}") + (f"  [{badge}]" if badge else "")
            self.set_fill_color(*bg_color)
            self.cell(0, 8, sanitize(title_text), fill=True, new_x="LMARGIN", new_y="NEXT")

            self.set_font("Helvetica", "", 9)
            self.set_text_color(70, 85, 100)
            self.set_x(14)
            self.multi_cell(0, 5, desc)
            self.ln(2)


    # ── Anomaly card ────────────────────────────────────────────────────


    def anomaly_card(self, rc: dict, idx: int):
        self.set_fill_color(254, 242, 242)
        self.set_x(10)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.RED)
        anomaly_types = rc.get("anomaly_types", ["numeric"])
        type_str = " + ".join(anomaly_types) if anomaly_types else "numeric"
        self.cell(0, 7, sanitize(f"  Row #{rc['row_index']}  [{type_str}]"),
                  fill=True, new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(60, 60, 60)
        for reason in rc.get("top_reasons", [])[:3]:
            col         = reason.get("column", "?")
            val         = reason.get("value", "?")
            reason_type = reason.get("type", "numeric")
            if reason_type == "categorical":
                reason_text = reason.get("reason", f"Unusual value '{val}' in column '{col}'")
                self.set_x(16)
                self.multi_cell(0, 5, sanitize(f"- {reason_text}"))
            else:
                normal_avg = reason.get("normal_avg")
                pct_diff   = reason.get("pct_diff")
                avg_s  = fmt_num(normal_avg) if normal_avg is not None else "N/A"
                diff_s = f"{pct_diff:+.1f}%" if isinstance(pct_diff, (int, float)) else "N/A"
                self.set_x(16)
                self.cell(0, 5,
                    sanitize(f"- {col}: {fmt_num(val)}  (avg: {avg_s},  deviation: {diff_s})"),
                    new_x="LMARGIN", new_y="NEXT")
        self.ln(2)


    # ── Correlation table ────────────────────────────────────────────────


    def correlation_table(self, correlations: dict):
        pairs = []
        for col_a, row in correlations.items():
            for col_b, val in row.items():
                if col_a >= col_b:
                    continue
                try:
                    pairs.append((col_a, col_b, float(val)))
                except (TypeError, ValueError):
                    pass
        pairs.sort(key=lambda x: abs(x[2]), reverse=True)

        if not pairs:
            self.body_text("No significant correlations found.")
            return

        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        self.cell(70, 8, "Column A",    fill=True)
        self.cell(70, 8, "Column B",    fill=True)
        self.cell(30, 8, "Correlation", fill=True, align="C")
        self.cell(20, 8, "Strength",    fill=True, align="C")
        self.ln()

        self.set_font("Helvetica", "", 9)
        for idx, (a, b, val) in enumerate(pairs[:10]):
            fill_color = (248, 250, 252) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)

            strength = "Strong" if abs(val) >= 0.7 else ("Moderate" if abs(val) >= 0.4 else "Weak")
            if val >= 0.7:
                self.set_text_color(*self.GREEN_TEXT)
            elif val <= -0.7:
                self.set_text_color(*self.RED)
            else:
                self.set_text_color(*self.DARK)

            self.cell(70, 7, sanitize(a[:28]), border="B", fill=True)
            self.cell(70, 7, sanitize(b[:28]), border="B", fill=True)
            self.cell(30, 7, f"{val:+.3f}",   border="B", fill=True, align="C")
            self.set_text_color(*self.GRAY)
            self.cell(20, 7, strength,         border="B", fill=True, align="C")
            self.ln()
        self.ln(4)


    # ── Segment table ────────────────────────────────────────────────────


    def segment_table(self, segment_sizes: dict, total_rows: int):
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        self.cell(40,  8, "Segment",    fill=True)
        self.cell(40,  8, "Row Count",  fill=True, align="C")
        self.cell(50,  8, "% of Total", fill=True, align="C")
        self.cell(60,  8, "Size",       fill=True, align="C")
        self.ln()

        colors = [
            (59, 130, 246), (168, 85, 247), (16, 185, 129),
            (245, 158, 11), (6, 182, 212), (236, 72, 153),
        ]
        self.set_font("Helvetica", "", 9)
        for idx, (seg, count) in enumerate(list(segment_sizes.items())[:8]):
            count_n = int(count)
            pct     = (count_n / total_rows * 100) if total_rows else 0
            color   = colors[idx % len(colors)]

            fill_color = (248, 250, 252) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)
            self.set_text_color(*self.DARK)
            self.cell(40, 7, sanitize(f"Segment {seg}"), border="B", fill=True)
            self.cell(40, 7, str(count_n), border="B", fill=True, align="C")
            self.cell(50, 7, f"{pct:.1f}%", border="B", fill=True, align="C")

            bar_x     = self.get_x() + 2
            bar_y     = self.get_y() + 1.5
            bar_total = 55
            bar_fill  = max(1, bar_total * pct / 100)
            self.set_fill_color(226, 232, 240)
            self.rect(bar_x, bar_y, bar_total, 4, "F")
            self.set_fill_color(*color)
            self.rect(bar_x, bar_y, bar_fill, 4, "F")
            self.cell(60, 7, "", border="B", fill=False)
            self.ln()
        self.ln(4)


    # ════════════════════════════════════════════════════════════
    #  COMPARISON-SPECIFIC RENDERING METHODS
    # ════════════════════════════════════════════════════════════


    # ── Two-file: metric breakdown table ────────────────────────


    def comparison_metric_table(self, rows: list, label1: str, label2: str):
        """
        Renders the per-metric breakdown for a two-file comparison.
        rows: list of dicts from metric_comparison array.
        """
        col_w = [52, 30, 30, 22, 20, 22, 14]
        headers = ["Metric", f"{label1[:10]} Avg", f"{label2[:10]} Avg",
                   "Change %", "Direction", "Sig?", ""]

        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        for i, h in enumerate(headers):
            align = "L" if i == 0 else "C"
            self.cell(col_w[i], 9, sanitize(h), fill=True, border=0, align=align)
        self.ln()

        self.set_font("Helvetica", "", 8)
        for idx, row in enumerate(rows[:25]):
            direction = row.get("direction", "stable")
            growth    = row.get("mean_change_pct", 0)
            significant = row.get("significant", False)

            fill_color = (248, 250, 255) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)

            avg1 = row.get(f"{label1}_mean") or row.get("mean_a") or row.get("value_1")
            avg2 = row.get(f"{label2}_mean") or row.get("mean_b") or row.get("value_2")

            col_name = sanitize(row.get("column", "").replace("_", " ").title()[:28])
            growth_s = f"{growth:+.1f}%" if isinstance(growth, (int, float)) else "-"
            dir_s    = "UP" if direction == "improved" else ("DN" if direction == "declined" else "-")
            sig_s    = "Yes" if significant else "-"

            cells = [col_name, fmt_num(avg1), fmt_num(avg2), growth_s, dir_s, sig_s, ""]
            for i, cell_val in enumerate(cells):
                if i == 3:  # growth %
                    try:
                        g = float(str(growth_s).replace("%", "").replace("+", ""))
                        self.set_text_color(*self.GREEN_TEXT if g >= 0 else self.RED)
                    except ValueError:
                        self.set_text_color(*self.DARK)
                elif i == 4:  # direction
                    self.set_text_color(*self.GREEN_TEXT if direction == "improved" else
                                         (self.RED if direction == "declined" else self.GRAY))
                else:
                    self.set_text_color(*self.DARK)
                align = "L" if i == 0 else "C"
                self.cell(col_w[i], 7, sanitize(str(cell_val)), border="B", fill=True, align=align)
            self.ln()
        self.ln(4)


    # ── Two-file: improved / declined badge lists ────────────────


    def comparison_badge_row(self, label: str, items: list, bg: tuple, text_color: tuple):
        """Renders a labeled row of tag-badges (improved / declined metrics)."""
        if not items:
            return
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*text_color)
        self.cell(0, 7, sanitize(f"  {label} ({len(items)})"), new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        line_items = []
        for m in items:
            tag = sanitize(m.replace("_", " ").title())
            line_items.append(tag)
        # Wrap into lines of ~120 chars
        line = ""
        for tag in line_items:
            candidate = (line + "  " + tag).strip()
            if len(candidate) > 100:
                self.set_x(14)
                self.set_fill_color(*bg)
                self.set_text_color(*text_color)
                self.cell(0, 6, sanitize(line), fill=True, new_x="LMARGIN", new_y="NEXT")
                line = tag
            else:
                line = candidate
        if line:
            self.set_x(14)
            self.set_fill_color(*bg)
            self.set_text_color(*text_color)
            self.cell(0, 6, sanitize(line), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)


    # ── Multi-file: per-file summary cards ──────────────────────


    def multi_file_summary_cards(self, per_file: list, selected_col: str = ""):
        """
        Renders a row of per-file summary cards (label, rows, columns, optional mean/total).
        """
        CARD_COLORS = [
            (124, 58, 237), (59, 130, 246), (16, 185, 129), (245, 158, 11),
            (220, 38, 38),  (236, 72, 153), (20, 184, 166), (249, 115, 22),
        ]
        card_w = 46
        gap    = 3
        per_row = 4
        start_x = 10

        for i, f in enumerate(per_file[:8]):
            col_idx = i % per_row
            if col_idx == 0 and i > 0:
                self.ln(32)
            x = start_x + col_idx * (card_w + gap)
            y = self.get_y()
            color = CARD_COLORS[i % len(CARD_COLORS)]

            # Card bg
            self.set_fill_color(248, 248, 254)
            self.set_draw_color(*color)
            self.set_line_width(0.4)
            self.rect(x, y, card_w, 28, "FD")

            # Color top accent
            self.set_fill_color(*color)
            self.rect(x, y, card_w, 3, "F")

            # Label
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*self.DARK)
            self.set_xy(x, y + 4)
            lbl = sanitize(str(f.get("label", f"File {i+1}")))
            if len(lbl) > 14:
                lbl = lbl[:12] + ".."
            self.cell(card_w, 5, lbl, align="C")

            # Rows / cols
            self.set_font("Helvetica", "", 7)
            self.set_text_color(*self.GRAY)
            self.set_xy(x, y + 9)
            self.cell(card_w, 5,
                sanitize(f"{f.get('rows', 0):,} rows / {f.get('columns', 0)} cols"),
                align="C")

            # Optional mean for selected_col
            if selected_col and f.get("means", {}).get(selected_col) is not None:
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(*color)
                self.set_xy(x, y + 14)
                self.cell(card_w, 5,
                    sanitize(f"Mean: {fmt_num(f['means'][selected_col])}"),
                    align="C")
                self.set_font("Helvetica", "", 7)
                self.set_text_color(*self.GRAY)
                self.set_xy(x, y + 19)
                self.cell(card_w, 5,
                    sanitize(f"Total: {fmt_num(f['totals'][selected_col])}"),
                    align="C")

            self.set_xy(start_x, y)
        self.ln(34)


    # ── Multi-file: trend analysis table ────────────────────────


    def multi_trend_table(self, labels: list, trend_analysis: dict, max_cols: int = 8):
        """
        Columns: Metric | File1 Mean | File2 Mean | ... | Overall Trend
        """
        shown_labels = labels[:6]  # cap at 6 files to fit width
        name_w  = 50
        val_w   = 22
        trend_w = 20
        total_w = name_w + val_w * len(shown_labels) + trend_w

        # Header
        self.set_font("Helvetica", "B", 7)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        self.cell(name_w, 8, "Metric", fill=True)
        CARD_COLORS = [
            (124, 58, 237), (59, 130, 246), (16, 185, 129),
            (245, 158, 11), (220, 38, 38),  (236, 72, 153),
        ]
        for j, lbl in enumerate(shown_labels):
            short = sanitize(lbl[:8])
            self.set_fill_color(*CARD_COLORS[j % len(CARD_COLORS)])
            self.cell(val_w, 8, short, fill=True, align="C")
        self.set_fill_color(*self.DARK)
        self.cell(trend_w, 8, "Trend", fill=True, align="C")
        self.ln()

        self.set_font("Helvetica", "", 7)
        cols = list(trend_analysis.keys())[:max_cols]
        for idx, col in enumerate(cols):
            data = trend_analysis[col]
            means = data.get("means", [])
            fill_color = (248, 250, 255) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)
            self.set_text_color(*self.DARK)
            self.cell(name_w, 6,
                sanitize(col.replace("_", " ").title()[:26]),
                border="B", fill=True)
            for j in range(len(shown_labels)):
                val = means[j] if j < len(means) else None
                self.set_text_color(*self.DARK)
                self.cell(val_w, 6,
                    fmt_num(val) if val is not None else "-",
                    border="B", fill=True, align="R")
            # Trend: compare first vs last mean
            if len(means) >= 2:
                try:
                    delta = float(means[-1]) - float(means[0])
                    t_sym = "UP" if delta > 0 else ("DN" if delta < 0 else "-")
                    self.set_text_color(*self.GREEN_TEXT if delta > 0 else
                                         (self.RED if delta < 0 else self.GRAY))
                except (TypeError, ValueError):
                    t_sym = "-"
                    self.set_text_color(*self.GRAY)
            else:
                t_sym = "-"
                self.set_text_color(*self.GRAY)
            self.cell(trend_w, 6, t_sym, border="B", fill=True, align="C")
            self.ln()
        self.ln(4)


    # ── Multi-file: growth rates table ──────────────────────────


    def multi_growth_table(self, growth_rates: dict, max_cols: int = 8):
        """
        Rows: metric. Columns: period transitions (A->B, B->C, ...).
        """
        if not growth_rates:
            self.body_text("No growth rate data available.")
            return

        # Gather all period pairs from first column
        sample_col = next(iter(growth_rates))
        transitions = [f"{g['from']}->{g['to']}" for g in growth_rates[sample_col]]
        shown_trans = transitions[:5]

        name_w  = 52
        val_w   = min(26, int((190 - name_w) / max(1, len(shown_trans))))

        # Header
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        self.cell(name_w, 8, "Metric", fill=True)
        for t in shown_trans:
            short = sanitize(t[:10])
            self.cell(val_w, 8, short, fill=True, align="C")
        self.ln()

        self.set_font("Helvetica", "", 8)
        cols = list(growth_rates.keys())[:max_cols]
        for idx, col in enumerate(cols):
            g_list = growth_rates[col][:5]
            fill_color = (248, 250, 255) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)
            self.set_text_color(*self.DARK)
            self.cell(name_w, 6,
                sanitize(col.replace("_", " ").title()[:28]),
                border="B", fill=True)
            for g in g_list:
                pct = g.get("growth_pct")
                if pct is not None:
                    try:
                        pct_f = float(pct)
                        self.set_text_color(*self.GREEN_TEXT if pct_f >= 0 else self.RED)
                        self.cell(val_w, 6, f"{pct_f:+.1f}%", border="B", fill=True, align="R")
                    except (TypeError, ValueError):
                        self.set_text_color(*self.GRAY)
                        self.cell(val_w, 6, "-", border="B", fill=True, align="R")
                else:
                    self.set_text_color(*self.GRAY)
                    self.cell(val_w, 6, "-", border="B", fill=True, align="R")
            self.ln()
        self.ln(4)


    # ── Multi-file: performance table (best/worst/total growth) ──


    def multi_performance_table(self, performance: dict):
        col_w = [52, 36, 36, 32, 34]
        headers = ["Metric", "Best Period", "Worst Period", "Total Growth", "Overall Trend"]

        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        for i, h in enumerate(headers):
            self.cell(col_w[i], 8, h, fill=True, align="C" if i > 0 else "L")
        self.ln()

        self.set_font("Helvetica", "", 8)
        for idx, (col, p) in enumerate(list(performance.items())[:20]):
            fill_color = (248, 250, 255) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)
            self.set_text_color(*self.DARK)

            tg  = p.get("total_growth_pct")
            tg_s = f"{tg:+.1f}%" if isinstance(tg, (int, float)) else "-"
            trend = p.get("overall_trend", "stable")
            t_s  = "UP" if trend == "upward" else ("DN" if trend == "downward" else "-")

            cells = [
                sanitize(col.replace("_", " ").title()[:28]),
                sanitize(str(p.get("best",  "-"))[:20]),
                sanitize(str(p.get("worst", "-"))[:20]),
                tg_s,
                t_s,
            ]
            for i, val in enumerate(cells):
                if i == 3:
                    try:
                        g = float(tg_s.replace("%", "").replace("+", ""))
                        self.set_text_color(*self.GREEN_TEXT if g >= 0 else self.RED)
                    except ValueError:
                        self.set_text_color(*self.DARK)
                elif i == 4:
                    self.set_text_color(*self.GREEN_TEXT if trend == "upward" else
                                         (self.RED if trend == "downward" else self.GRAY))
                else:
                    self.set_text_color(*self.DARK)
                align = "L" if i == 0 else "C"
                self.cell(col_w[i], 6, val, border="B", fill=True, align=align)
            self.ln()
        self.ln(4)


    # ── Multi-file: schema stability banner ─────────────────────


    def schema_stability_banner(self, column_evolution: dict):
        score = column_evolution.get("schema_stability", 0)
        color = self.GREEN_TEXT if score >= 80 else (self.ORANGE if score >= 50 else self.RED)
        label = "Stable" if score >= 80 else ("Moderate" if score >= 50 else "Unstable")

        self.set_fill_color(248, 250, 252)
        self.set_draw_color(*color)
        self.set_line_width(0.5)
        self.rect(10, self.get_y(), 190, 14, "FD")

        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*color)
        self.set_x(14)
        self.cell(0, 7, sanitize(f"Schema Stability: {score}%  —  {label}"),
                  new_x="LMARGIN", new_y="NEXT")

        counts = [
            ("Common",  column_evolution.get("common_columns",  []), self.GREEN_TEXT),
            ("Partial", column_evolution.get("partial_columns", []), self.ORANGE),
            ("Unique",  column_evolution.get("unique_columns",  []), self.GRAY),
            ("New",     column_evolution.get("new_columns",     []), self.BLUE),
            ("Dropped", column_evolution.get("dropped_columns", []), self.RED),
        ]
        self.set_font("Helvetica", "", 8)
        self.set_x(14)
        parts = []
        for name, lst, _ in counts:
            parts.append(f"{name}: {len(lst)}")
        self.set_text_color(*self.GRAY)
        self.cell(0, 7, sanitize("  |  ".join(parts)), new_x="LMARGIN", new_y="NEXT")
        self.ln(3)


    # ── Multi-file: column presence matrix ──────────────────────


    def column_presence_matrix(self, column_evolution: dict, labels: list):
        all_cols      = column_evolution.get("all_columns", [])
        presence      = column_evolution.get("presence_matrix", {})
        shown_labels  = labels[:6]

        name_w = 55
        cell_w = min(20, int((190 - name_w - 20) / max(1, len(shown_labels))))
        pct_w  = 20

        self.set_font("Helvetica", "B", 7)
        self.set_fill_color(*self.DARK)
        self.set_text_color(*self.WHITE)
        self.cell(name_w, 8, "Column", fill=True)
        CARD_COLORS = [
            (124, 58, 237), (59, 130, 246), (16, 185, 129),
            (245, 158, 11), (220, 38, 38),  (236, 72, 153),
        ]
        for j, lbl in enumerate(shown_labels):
            self.set_fill_color(*CARD_COLORS[j % len(CARD_COLORS)])
            self.cell(cell_w, 8, sanitize(lbl[:7]), fill=True, align="C")
        self.set_fill_color(*self.DARK)
        self.cell(pct_w, 8, "Cov%", fill=True, align="C")
        self.ln()

        self.set_font("Helvetica", "", 7)
        for idx, col in enumerate(all_cols[:30]):
            row    = presence.get(col, {})
            count  = sum(1 for l in labels if row.get(l))
            pct    = int(count / len(labels) * 100) if labels else 0
            is_all = count == len(labels)
            is_one = count == 1

            fill_color = (248, 250, 255) if idx % 2 == 0 else (255, 255, 255)
            self.set_fill_color(*fill_color)
            name_color = self.DARK if is_all else (self.LIGHT_GRAY if is_one else (217, 119, 6))
            self.set_text_color(*name_color)
            self.cell(name_w, 5,
                sanitize(col.replace("_", " ").title()[:28]),
                border="B", fill=True)
            for j, lbl in enumerate(shown_labels):
                present = row.get(lbl, False)
                self.set_text_color(*self.GREEN_TEXT if present else self.LIGHT_GRAY)
                self.cell(cell_w, 5,
                    "Y" if present else "-",
                    border="B", fill=True, align="C")
            pct_color = self.GREEN_TEXT if pct == 100 else (self.ORANGE if pct >= 50 else self.RED)
            self.set_text_color(*pct_color)
            self.cell(pct_w, 5, f"{pct}%", border="B", fill=True, align="C")
            self.ln()
        self.ln(4)


    # ── Multi-file: schema per-period diff cards ─────────────────


    def schema_diff_cards(self, per_period_stats: list):
        """One card per file showing added/removed columns vs previous."""
        CARD_COLORS = [
            (124, 58, 237), (59, 130, 246), (16, 185, 129),
            (245, 158, 11), (220, 38, 38),  (236, 72, 153),
        ]
        for i, ps in enumerate(per_period_stats[:6]):
            color = CARD_COLORS[i % len(CARD_COLORS)]
            self.set_fill_color(248, 248, 254)
            self.set_draw_color(*color)
            self.set_line_width(0.3)
            self.rect(10, self.get_y(), 190, 4, "F")

            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*self.DARK)
            label_text = sanitize(ps.get("label", f"File {i+1}"))
            total_cols = ps.get("total_cols", "?")
            self.set_x(12)
            self.cell(0, 7, sanitize(f"{label_text}  ({total_cols} columns)"),
                      new_x="LMARGIN", new_y="NEXT")

            if i == 0:
                self.set_font("Helvetica", "I", 7)
                self.set_text_color(*self.GRAY)
                self.set_x(16)
                self.cell(0, 5, "Baseline file", new_x="LMARGIN", new_y="NEXT")
            else:
                added   = ps.get("new_vs_prev", [])
                dropped = ps.get("dropped_vs_prev", [])
                if not added and not dropped:
                    self.set_font("Helvetica", "I", 7)
                    self.set_text_color(*self.GREEN_TEXT)
                    self.set_x(16)
                    self.cell(0, 5, "Schema unchanged vs previous file",
                              new_x="LMARGIN", new_y="NEXT")
                else:
                    if added:
                        self.set_font("Helvetica", "", 7)
                        self.set_text_color(*self.GREEN_TEXT)
                        self.set_x(16)
                        added_str = ", ".join(sanitize(c) for c in added[:6])
                        if len(added) > 6:
                            added_str += f" +{len(added)-6} more"
                        self.cell(0, 5, sanitize(f"+ Added: {added_str}"),
                                  new_x="LMARGIN", new_y="NEXT")
                    if dropped:
                        self.set_font("Helvetica", "", 7)
                        self.set_text_color(*self.RED)
                        self.set_x(16)
                        drop_str = ", ".join(sanitize(c) for c in dropped[:6])
                        if len(dropped) > 6:
                            drop_str += f" +{len(dropped)-6} more"
                        self.cell(0, 5, sanitize(f"- Removed: {drop_str}"),
                                  new_x="LMARGIN", new_y="NEXT")
            self.ln(3)



# ── Main entry point (analysis) ────────────────────────────────────────────


def generate_pdf(
    domain:       dict,
    data_quality: dict,
    kpis:         dict,
    anomalies:    dict,
    insights:     dict,
    file_id:      str,
    forecast:     dict = None,
    ml_analysis:  dict = None,
) -> bytes:

    pdf = BizlyticsPDF()
    pdf.set_auto_page_break(auto=True, margin=22)

    domain_label  = domain.get("label", "General Dataset") if domain else "General Dataset"
    anomaly_count = anomalies.get("anomaly_count", 0)

    # Cover
    pdf.add_page()
    pdf.cover_page(domain_label, file_id, data_quality, anomaly_count)

    # Content
    pdf.add_page()

    pdf.section_title("Dataset Overview")
    stats = [
        ("Total Rows",      data_quality.get("total_rows",    "N/A")),
        ("Total Columns",   data_quality.get("total_columns", "N/A")),
        ("Quality Score",   f"{data_quality.get('quality_score', 'N/A')}/100"),
        ("Missing Data",    f"{data_quality.get('missing_pct', 'N/A')}%"),
        ("Duplicate Rows",  data_quality.get("duplicate_rows", 0)),
        ("Anomalies Found", anomaly_count),
    ]
    pdf.stat_grid(stats)

    missing = data_quality.get("missing_values", {})
    high_missing = {k: v for k, v in missing.items() if isinstance(v, dict) and v.get("pct", 0) > 5}
    if high_missing:
        pdf.sub_title("Columns with High Missing Values (>5%)")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*pdf.GRAY)
        for col, info in list(high_missing.items())[:8]:
            pdf.cell(0, 5, sanitize(f"  - {col}: {info.get('count', 0)} missing ({info.get('pct', 0):.1f}%)"),
                     new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    if insights.get("executive_summary"):
        pdf.section_title("AI Executive Summary", pdf.BG_PURPLE)
        pdf.set_fill_color(*pdf.BG_PURPLE)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 30, 100)
        pdf.set_x(10)
        pdf.multi_cell(0, 7, sanitize(f"  {insights['executive_summary']}"), fill=True)
        pdf.ln(4)

    if kpis:
        clean_kpis = {k: v for k, v in kpis.items() if k != "_domain_kpis"}
        if clean_kpis:
            pdf.section_title("Key Performance Indicators")
            pdf.kpi_table(clean_kpis)
        domain_kpis = kpis.get("_domain_kpis", {})
        if domain_kpis and isinstance(domain_kpis, dict):
            pdf.sub_title(f"{domain_label} — Smart KPIs")
            pdf.domain_kpi_table(domain_kpis)

    if insights.get("trends"):
        pdf.section_title("Trends Identified", pdf.BG_GREEN)
        pdf.insight_cards(insights["trends"], pdf.BG_GREEN, pdf.GREEN_TEXT)

    if insights.get("risks"):
        pdf.section_title("Risks Identified", pdf.BG_RED)
        pdf.insight_cards(insights["risks"], pdf.BG_RED, pdf.RED)

    if insights.get("opportunities"):
        pdf.section_title("Opportunities", pdf.BG_YELLOW)
        pdf.insight_cards(insights["opportunities"], pdf.BG_YELLOW, pdf.ORANGE)

    if insights.get("recommendations"):
        pdf.section_title("Recommendations")
        for i, rec in enumerate(insights["recommendations"][:6], 1):
            priority = rec.get("priority", "").upper()
            action   = sanitize(rec.get("action", ""))
            outcome  = sanitize(rec.get("outcome", ""))
            p_color  = pdf.RED if priority == "HIGH" else (pdf.ORANGE if priority == "MEDIUM" else pdf.GREEN_TEXT)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*p_color)
            pdf.cell(0, 7, sanitize(f"  {i}. [{priority}] {action}"),
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 95, 110)
            pdf.set_x(18)
            pdf.multi_cell(0, 5, sanitize(f"Expected outcome: {outcome}"))
            pdf.ln(1)
        pdf.ln(3)

    if forecast and forecast.get("forecast"):
        pdf.section_title("90-Day Forecast Summary")
        trend_dir = forecast.get("trend_direction", "stable")
        fc_rows   = forecast["forecast"]
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*pdf.GRAY)
        pdf.cell(0, 6,
            sanitize(f"  Model: Prophet  |  Periods: {len(fc_rows)}  |  Trend: {trend_dir.upper()}  |  Confidence: 80%"),
            new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(*pdf.DARK)
        pdf.set_text_color(*pdf.WHITE)
        pdf.cell(70, 8, "Date",         fill=True)
        pdf.cell(45, 8, "Forecast",     fill=True, align="R")
        pdf.cell(45, 8, "Lower Bound",  fill=True, align="R")
        pdf.cell(30, 8, "Upper Bound",  fill=True, align="R")
        pdf.ln()

        pdf.set_font("Helvetica", "", 9)
        sample = fc_rows[::max(1, len(fc_rows)//10)][:10]
        for idx, row in enumerate(sample):
            fill_color = (248, 250, 252) if idx % 2 == 0 else (255, 255, 255)
            pdf.set_fill_color(*fill_color)
            pdf.set_text_color(*pdf.DARK)
            pdf.cell(70, 6, sanitize(str(row.get("ds", ""))[:22]),  border="B", fill=True)
            pdf.cell(45, 6, fmt_num(row.get("yhat")),               border="B", fill=True, align="R")
            pdf.cell(45, 6, fmt_num(row.get("yhat_lower")),         border="B", fill=True, align="R")
            pdf.cell(30, 6, fmt_num(row.get("yhat_upper")),         border="B", fill=True, align="R")
            pdf.ln()
        pdf.ln(4)

    correlations = data_quality.get("correlations", {})
    if correlations and len(correlations) > 1:
        pdf.section_title("Correlation Analysis")
        pdf.body_text("Top correlations between numeric columns. Strong positive (>=0.7) or negative (<=-0.7) correlations are highlighted.")
        pdf.correlation_table(correlations)

    if ml_analysis and ml_analysis.get("segment_sizes"):
        pdf.section_title("Customer / Data Segments", pdf.BG_PURPLE)
        seg_count  = ml_analysis.get("segment_count", len(ml_analysis["segment_sizes"]))
        total_rows = data_quality.get("total_rows", 1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*pdf.GRAY)
        pdf.cell(0, 6,
            sanitize(f"  Algorithm: K-Means clustering + PCA visualization  |  Segments found: {seg_count}"),
            new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        pdf.segment_table(ml_analysis["segment_sizes"], total_rows)
        sizes = [int(v) for v in ml_analysis["segment_sizes"].values()]
        if sizes:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*pdf.GRAY)
            pdf.cell(0, 5,
                sanitize(f"  Largest segment: {max(sizes)} rows  |  Smallest: {min(sizes)} rows  |  Avg: {sum(sizes)//len(sizes)} rows"),
                new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)

    if anomaly_count > 0:
        pdf.section_title(f"Anomaly Detection  -  {anomaly_count} anomalies detected", pdf.BG_RED)
        det = anomalies.get("detection_summary", {})
        if det:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*pdf.GRAY)
            pdf.cell(0, 6, sanitize(
                f"  Numeric consensus: {det.get('numeric_consensus_flagged', 0)}  |  "
                f"Group-aware: {det.get('group_aware_flagged', 0)}  |  "
                f"Categorical: {det.get('categorical_flagged', 0)}"
            ), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
        else:
            pdf.info_box(
                "Detection method: Isolation Forest + DBSCAN consensus. "
                "Only rows flagged by both models are marked as anomalies.",
                pdf.BG_RED, (120, 30, 30)
            )
        for rc in (anomalies.get("root_causes") or [])[:8]:
            pdf.anomaly_card(rc, 0)
        soft = anomalies.get("soft_categorical_flags", [])
        if soft:
            pdf.sub_title(f"Soft Categorical Signals  ({len(soft)} rows)")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(100, 80, 0)
            for flag in soft[:5]:
                reasons = "; ".join(flag.get("reasons", []))
                pdf.set_x(14)
                pdf.multi_cell(0, 5, sanitize(f"Row #{flag['row_index']}: {reasons}"))
            pdf.ln(2)
    elif anomaly_count == 0:
        pdf.section_title("Anomaly Detection", pdf.BG_GREEN)
        pdf.info_box(
            "No anomalies detected — your dataset appears healthy. "
            "Isolation Forest + DBSCAN consensus found no rows that simultaneously "
            "violate both models thresholds.",
            pdf.BG_GREEN, pdf.GREEN_TEXT
        )

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*pdf.LIGHT_GRAY)
    pdf.multi_cell(0, 5,
        "This report was automatically generated by Bizlytics AI. "
        "AI-generated insights should be treated as decision support and validated with domain expertise. "
        f"Report generated: {datetime.now().strftime('%d %B %Y at %I:%M %p')}."
    )

    return bytes(pdf.output())


# ── Comparison entry point ──────────────────────────────────────────────────


def generate_comparison_pdf(comparison_result: dict) -> bytes:
    """
    Generate a PDF for either a two-file or multi-file comparison result.

    The function auto-detects the mode by checking for the presence of
    'label1' / 'label2' (two-file) vs 'labels' list with >2 entries (multi).

    Args:
        comparison_result: The full JSON payload returned by /compare or /compare/multi.

    Returns:
        PDF as raw bytes, ready to stream or save.
    """
    pdf = BizlyticsPDF()
    pdf.set_auto_page_break(auto=True, margin=22)

    # ── Detect mode ───────────────────────────────────────────────────────
    if "label1" in comparison_result and "label2" in comparison_result:
        mode   = "two"
        label1 = comparison_result.get("label1", "Dataset A")
        label2 = comparison_result.get("label2", "Dataset B")
        labels = [label1, label2]
    else:
        mode   = "multi"
        labels = comparison_result.get("labels", [])
        label1 = labels[0] if labels else "File 1"
        label2 = labels[1] if len(labels) > 1 else "File 2"

    summary  = comparison_result.get("summary", {})
    metrics_compared    = summary.get("total_metrics_compared", 0)
    significant_changes = summary.get("significant_changes", len(summary.get("improved_metrics", [])) + len(summary.get("declined_metrics", [])))
    file_count = comparison_result.get("file_count", len(labels))
    narrative  = comparison_result.get("narrative", "")

    # ── Cover ─────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.cover_page_comparison(
        mode=mode,
        labels=labels,
        metrics_compared=metrics_compared,
        significant_changes=significant_changes,
        file_count=file_count,
    )

    # ── Content page(s) ───────────────────────────────────────────────────
    pdf.add_page()


    # ════════════════════════════════════════════════════════════════════
    #  TWO-FILE COMPARISON
    # ════════════════════════════════════════════════════════════════════
    if mode == "two":
        overview = comparison_result.get("overview", {})

        # Overview stats
        pdf.section_title("Comparison Overview")
        stats = [
            (f"{label1} Rows",       overview.get(label1, {}).get("rows", "N/A")),
            (f"{label2} Rows",       overview.get(label2, {}).get("rows", "N/A")),
            ("Metrics Compared",     metrics_compared),
            ("Significant Changes",  significant_changes),
            ("Improved Metrics",     len(summary.get("improved_metrics", []))),
            ("Declined Metrics",     len(summary.get("declined_metrics", []))),
        ]
        pdf.stat_grid(stats)

        # AI Narrative
        if narrative:
            pdf.section_title("AI Comparison Analysis", pdf.BG_PURPLE)
            pdf.set_fill_color(*pdf.BG_PURPLE)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 30, 100)
            pdf.set_x(10)
            pdf.multi_cell(0, 7, sanitize(f"  {narrative}"), fill=True)
            pdf.ln(4)

        # Improved / declined badge rows
        improved = summary.get("improved_metrics", [])
        declined = summary.get("declined_metrics", [])
        if improved or declined:
            pdf.section_title("Metric Outcomes")
            if improved:
                pdf.comparison_badge_row("Improved", improved, pdf.BG_GREEN, pdf.GREEN_TEXT)
            if declined:
                pdf.comparison_badge_row("Declined", declined, pdf.BG_RED, pdf.RED)

        # Detailed metric breakdown
        metric_rows = comparison_result.get("metric_comparison", [])
        if metric_rows:
            pdf.section_title("Detailed Metric Breakdown")
            pdf.body_text(
                f"Mean values for each shared numeric column across {label1} and {label2}. "
                "Growth % is computed as ((B - A) / |A|) x 100."
            )
            pdf.comparison_metric_table(metric_rows, label1, label2)

        # Column-level overview from overview dict (numeric stats per dataset)
        for ds_label, ds_data in overview.items():
            col_stats = ds_data.get("column_stats", {})
            if not col_stats:
                continue
            pdf.sub_title(f"{ds_label} — Column Statistics")
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(*pdf.DARK)
            pdf.set_text_color(*pdf.WHITE)
            for h, w in [("Column", 60), ("Mean", 32), ("Std Dev", 32), ("Min", 28), ("Max", 28), ("Missing%", 10)]:
                pdf.cell(w, 7, h, fill=True, align="C" if h != "Column" else "L")
            pdf.ln()
            pdf.set_font("Helvetica", "", 8)
            for ci, (col, cs) in enumerate(list(col_stats.items())[:15]):
                fc = (248, 250, 255) if ci % 2 == 0 else (255, 255, 255)
                pdf.set_fill_color(*fc)
                pdf.set_text_color(*pdf.DARK)
                pdf.cell(60, 6, sanitize(col.replace("_", " ").title()[:28]), border="B", fill=True)
                pdf.cell(32, 6, fmt_num(cs.get("mean")),  border="B", fill=True, align="R")
                pdf.cell(32, 6, fmt_num(cs.get("std")),   border="B", fill=True, align="R")
                pdf.cell(28, 6, fmt_num(cs.get("min")),   border="B", fill=True, align="R")
                pdf.cell(28, 6, fmt_num(cs.get("max")),   border="B", fill=True, align="R")
                miss_pct = cs.get("missing_pct", 0)
                pdf.set_text_color(*pdf.RED if miss_pct > 10 else pdf.DARK)
                pdf.cell(10, 6, f"{miss_pct:.0f}%", border="B", fill=True, align="C")
                pdf.ln()
            pdf.ln(4)


    # ════════════════════════════════════════════════════════════════════
    #  MULTI-FILE COMPARISON
    # ════════════════════════════════════════════════════════════════════
    else:
        per_file       = comparison_result.get("per_file", [])
        trend_analysis = comparison_result.get("trend_analysis", {})
        growth_rates   = comparison_result.get("growth_rates", {})
        performance    = comparison_result.get("performance", {})
        column_evol    = comparison_result.get("column_evolution", {})
        partial_anal   = comparison_result.get("partial_analysis", [])
        common_cols    = comparison_result.get("common_columns", [])
        selected_col   = common_cols[0] if common_cols else ""

        # Overview stats
        pdf.section_title("Multi-Period Overview")
        stats = [
            ("Files Compared",    file_count),
            ("Metrics Tracked",   metrics_compared),
            ("Improving Metrics", len(summary.get("improved_metrics", []))),
            ("Declining Metrics", len(summary.get("declined_metrics", []))),
            ("Common Columns",    len(common_cols)),
            ("Partial Columns",   len(comparison_result.get("column_evolution", {}).get("partial_columns", []))),
        ]
        pdf.stat_grid(stats)

        # Schema stability banner
        if column_evol:
            pdf.schema_stability_banner(column_evol)

        # AI Narrative
        if narrative:
            pdf.section_title("AI Multi-Period Analysis", pdf.BG_PURPLE)
            pdf.set_fill_color(*pdf.BG_PURPLE)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 30, 100)
            pdf.set_x(10)
            pdf.multi_cell(0, 7, sanitize(f"  {narrative}"), fill=True)
            pdf.ln(4)

        # Improved / declined
        improved = summary.get("improved_metrics", [])
        declined = summary.get("declined_metrics", [])
        if improved or declined:
            pdf.section_title("Overall Metric Outcomes")
            if improved:
                pdf.comparison_badge_row("Improving Overall", improved, pdf.BG_GREEN, pdf.GREEN_TEXT)
            if declined:
                pdf.comparison_badge_row("Declining Overall", declined, pdf.BG_RED, pdf.RED)

        # Per-file summary cards
        if per_file:
            pdf.section_title("Per-File Summary")
            pdf.multi_file_summary_cards(per_file, selected_col)

        # Trend analysis table
        if trend_analysis:
            pdf.section_title("Mean Trend Across Files")
            pdf.body_text(
                f"Mean value of each shared metric per file. "
                f"'Trend' column compares first vs last file (UP/DN/-)."
            )
            pdf.multi_trend_table(labels, trend_analysis)

        # Growth rates table
        if growth_rates:
            pdf.section_title("Period-over-Period Growth Rates")
            pdf.body_text("Growth % between consecutive files for each shared metric.")
            pdf.multi_growth_table(growth_rates)

        # Performance table
        if performance:
            pdf.section_title("Performance Summary  —  Best / Worst / Total Growth")
            pdf.multi_performance_table(performance)

        # Schema changes per file
        per_period_stats = column_evol.get("per_period_stats", [])
        if per_period_stats:
            pdf.section_title("Schema Changes Per File", pdf.BG_INDIGO)
            pdf.body_text("Each file compared to its predecessor for added/removed columns.")
            pdf.schema_diff_cards(per_period_stats)

        # Column presence matrix
        if column_evol.get("all_columns"):
            pdf.section_title("Column Presence Matrix")
            pdf.body_text(
                "Y = column present in that file, - = absent. "
                "Coverage % shows how many files contain each column."
            )
            pdf.column_presence_matrix(column_evol, labels)

        # Partial columns analysis
        if partial_anal:
            pdf.section_title(f"Partial Column Analysis  ({len(partial_anal)} columns)", pdf.BG_YELLOW)
            pdf.body_text("Columns present in some but not all files, still analysed with available data.")
            for entry in partial_anal[:10]:
                col_name  = sanitize(entry.get("column", "").replace("_", " ").title())
                coverage  = entry.get("coverage_pct", 0)
                avail_in  = entry.get("available_in", [])
                trend     = entry.get("overall_trend", "stable")

                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(*pdf.ORANGE)
                pdf.cell(0, 7,
                    sanitize(f"  {col_name}  —  {coverage}% coverage  ({len(avail_in)} of {file_count} files)  |  Trend: {trend.upper()}"),
                    new_x="LMARGIN", new_y="NEXT")

                per_period = entry.get("per_period", [])
                if per_period:
                    pdf.set_font("Helvetica", "B", 7)
                    pdf.set_fill_color(*pdf.DARK)
                    pdf.set_text_color(*pdf.WHITE)
                    for h, w in [("File", 50), ("Mean", 30), ("Total", 35), ("Std Dev", 30), ("Count", 25), ("Best/Worst", 20)]:
                        pdf.cell(w, 6, h, fill=True, align="C" if h != "File" else "L")
                    pdf.ln()
                    best_p  = entry.get("best_period")
                    worst_p = entry.get("worst_period")
                    pdf.set_font("Helvetica", "", 7)
                    for pi, pp in enumerate(per_period):
                        fc = (248, 250, 255) if pi % 2 == 0 else (255, 255, 255)
                        pdf.set_fill_color(*fc)
                        pdf.set_text_color(*pdf.DARK)
                        pdf.cell(50, 5, sanitize(str(pp.get("label", ""))[:20]), border="B", fill=True)
                        pdf.cell(30, 5, fmt_num(pp.get("mean")),  border="B", fill=True, align="R")
                        pdf.cell(35, 5, fmt_num(pp.get("total")), border="B", fill=True, align="R")
                        pdf.cell(30, 5, fmt_num(pp.get("std")),   border="B", fill=True, align="R")
                        pdf.cell(25, 5, str(int(pp.get("count", 0))), border="B", fill=True, align="R")
                        flag_lbl = pp.get("label", "")
                        if flag_lbl == best_p:
                            pdf.set_text_color(*pdf.GREEN_TEXT)
                            pdf.cell(20, 5, "BEST",  border="B", fill=True, align="C")
                        elif flag_lbl == worst_p:
                            pdf.set_text_color(*pdf.RED)
                            pdf.cell(20, 5, "WORST", border="B", fill=True, align="C")
                        else:
                            pdf.cell(20, 5, "-", border="B", fill=True, align="C")
                        pdf.ln()
                pdf.ln(4)


    # ── Footer note ────────────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*pdf.LIGHT_GRAY)
    pdf.multi_cell(0, 5,
        "This comparison report was automatically generated by Bizlytics AI. "
        "AI-generated insights should be treated as decision support and validated with domain expertise. "
        f"Report generated: {datetime.now().strftime('%d %B %Y at %I:%M %p')}."
    )

    return bytes(pdf.output())
